import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <div className="py-0 px-8">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen py-16 px-0 flex flex-1 flex-col justify-center items-center">
        <h1 className="m-0 leading-[1.15] text-6xl text-center">
          Welcome to
          <a
            className="ml-2 text-blue-600 no-underline hover:underline focus:underline active:underline"
            href="https://nextjs.org"
          >
            Next.js!
          </a>
        </h1>

        <p className="text-center my-16 mx-0 leading-6 text-2xl">
          Get started by editing
          <code className="ml-2 bg-zinc-200 rounded-md p-3 text-base font-mono">
            pages/index.tsx
          </code>
        </p>

        <div className="flex items-center justify-center flex-wrap max-w-[800px]">
          <a
            href="https://nextjs.org/docs"
            className="m-4 p-6 text-center text-inherit no-underline border-solid border-[1px] border-gray-200 rounded-[10px] transition-colors max-w-[300px] hover:text-blue-600 focus:text-blue-600 active:text-blue-600 hover:border-blue-600 focus:border-blue-600 active:border-blue-600"
          >
            <h2 className="mx-0 mt-0 mb-4 text-2xl">Documentation &rarr;</h2>
            <p className="m-0 text-xl leading-[1.5]">
              Find in-depth information about Next.js features and API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn"
            className="m-4 p-6 text-center text-inherit no-underline border-solid border-[1px] border-gray-200 rounded-[10px] transition-colors max-w-[300px] hover:text-blue-600 focus:text-blue-600 active:text-blue-600 hover:border-blue-600 focus:border-blue-600 active:border-blue-600"
          >
            <h2 className="mx-0 mt-0 mb-4 text-2xl">Learn &rarr;</h2>
            <p className="m-0 text-xl leading-[1.5]">
              Learn about Next.js in an interactive course with quizzes!
            </p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className="m-4 p-6 text-center text-inherit no-underline border-solid border-[1px] border-gray-200 rounded-[10px] transition-colors max-w-[300px] hover:text-blue-600 focus:text-blue-600 active:text-blue-600 hover:border-blue-600 focus:border-blue-600 active:border-blue-600"
          >
            <h2 className="mx-0 mt-0 mb-4 text-2xl">Examples &rarr;</h2>
            <p className="m-0 text-xl leading-[1.5]">
              Discover and deploy boilerplate example Next.js projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className="m-4 p-6 text-center text-inherit no-underline border-solid border-[1px] border-gray-200 rounded-[10px] transition-colors max-w-[300px] hover:text-blue-600 focus:text-blue-600 active:text-blue-600 hover:border-blue-600 focus:border-blue-600 active:border-blue-600"
          >
            <h2 className="mx-0 mt-0 mb-4 text-2xl">Deploy &rarr;</h2>
            <p className="m-0 text-xl leading-[1.5]">
              Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nemo cum
              ea totam.
            </p>
          </a>
        </div>
      </main>

      <footer className="flex flex-1 py-8 px-0 border-t-[1px] border-t-gray-200 border-solid justify-center items-center">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
          className="flex flex-grow justify-center items-center"
        >
          Powered by
          <span className="h-4 ml-2">
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
